# This is a basic workflow to help you get started with Actions

name: Run News

# Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "0 3,19 * * *"
  # "0 */8 * * *" - “At minute 0 past every 8th hour.”
  # "*/5 * * * *" - After every 5 minutes
  # "0 6/12 * * *" - At minute 0 past every 12th hour from 6 through 23.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  categorize_news_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      
      # If using Python:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      # If using Python:
      - name: Install dependencies
        run: pip install --upgrade --force-reinstall -r cyber_web/ml_code/requirements.txt
        
      # If using Python:
      - name: Install nltk downloads
        run: python -m nltk.downloader punkt stopwords wordnet omw-1.4
        
      # If using Python:
      - name: Pull data
        run: python cyber_web/ml_code/news_main.py
      
      #
      #    
      # NOTE: This commits everything in the `data` directory. Make sure this matches your needs
      - name: Git commit
        run: |
          git add cyber_web -A
          if ! git diff-index --quiet HEAD; then
            git config --local user.email "mailcyberbytes@gmail.com"
            git config --local user.name "GitHub Action"
            git commit -m "Commiting Category data"
          fi
          
      # NOTE: Check that your branch name is correct here
      - name: Git push
        run: |
          echo ${GITHUB_ACTOR}
          echo ${TOKEN}
          echo ${GITHUB_REPOSITORY}
          echo "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
